version: '3.1'
services:
  ctfire-zuul:
    restart: always
    image: 192.168.110.132:5000/ctfire-zuul
    container_name: ctfire-zuul
    ports:
      - 8769:8769
    networks:
      - zuul_network

networks:
  zuul_network: