version: '3.1'
services:
  ctfire-service-sso:
    restart: always
    image: 192.168.110.132:5000/ctfire-service-sso
    container_name: ctfire-service-sso
    ports:
      - 8503:8503
    networks:
      - service_sso_network

networks:
  service_sso_network: