version: '3.1'
services:
  ctfire-zipkin:
    restart: always
    image: 192.168.110.132:5000/ctfire-zipkin
    container_name: ctfire-zipkin
    ports:
      - 9411:9411
    networks:
      - zipkin_network

networks:
  zipkin_network: