version: '3.1'
services:
  ctfire-service-user:
    restart: always
    image: 192.168.110.132:5000/ctfire-web-device
    container_name: ctfire-web-device
    ports:
      - 8602:8602
    networks:
      - service_web_device_network

networks:
  service_web_device_network: