version: '3.1'
services:
  ctfire-service-user:
    restart: always
    image: 192.168.110.132:5000/ctfire-web-backend
    container_name: ctfire-web-backend
    ports:
      - 8603:8603
    networks:
      - service_web_backend_network

networks:
  service_web_backend_network: