version: '3.1'
services:
  ctfire-service-redis:
    restart: always
    image: 192.168.110.132:5000/ctfire-service-redis
    container_name: ctfire-service-redis
    ports:
      - 8502:8502
    networks:
      - service_redis_network

networks:
  service_redis_network: