version: '3.1'
services:
  ctfire-service-user:
    restart: always
    image: 192.168.110.132:5000/ctfire-service-user
    container_name: ctfire-service-user
    ports:
      - 8501:8501
    networks:
      - service_user_network

networks:
  service_user_network: