version: '3.1'
services:
  ctfire-service-user:
    restart: always
    image: 192.168.110.132:5000/ctfire-web-user
    container_name: ctfire-web-user
    ports:
      - 8601:8601
    networks:
      - service_web_user_network

networks:
  service_web_user_network: