version: '3.1'
services:
  ctfire-zipkin:
    restart: always
    image: 192.168.110.132:5000/ctfire-admin
    container_name: ctfire-admin
    ports:
      - 8084:8084
    networks:
      - admin_network

networks:
  admin_network: